/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Lap3;

import java.awt.event.ActionEvent;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author namxg
 */
public class JFrameQLSV extends javax.swing.JFrame {

    /**
     * Creates new form JFrameQLSV
     */
    ArrayList<SinhVien> lstStudent = new ArrayList<>();

    public JFrameQLSV() {
        initComponents();
        this.CapNhat();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    private void CapNhat() {
        this.txtHoTen.setText("");
        this.txtDiem.setText("");
        this.txtHocLuc.setText("");
        this.cbbNganh.removeAllItems();
        this.cbbNganh.addItem("Ứng Dụng Phần Mềm");
        this.cbbNganh.addItem("Lập trình máy tính & thiết bị di động");
        this.cbbNganh.addItem("Thiết kế web");
        this.cbbNganh.addItem("Tự động hóa");
        this.cbbNganh.addItem("Quản trị khách sạn");
        this.chkBonus.setSelected(false);
    }

    public void fillToTable() {
        DefaultTableModel model = (DefaultTableModel) tblSinhVien.getModel();
        model.setRowCount(0);

        for (SinhVien sv : lstStudent) {
            model.addRow(new Object[]{sv.getName(), sv.getMarks(), sv.getMajor(), sv.getGrade(), sv.isBonus()});
        }
    }

    public boolean checkTrung(String name) {
        boolean check = false;
        for (int i = 0; i < lstStudent.size(); i++) {
            if (lstStudent.get(i).getName().equals(name)) {
                check = true;
            }
        }
        return check;
    }

    public void themSinhVien() {
        try {
            if (txtHoTen.getText().isEmpty() || txtDiem.getText().isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "Không được để rỗng");
            } else if (checkTrung(txtHoTen.getText()) == true) {
                JOptionPane.showMessageDialog(rootPane, "Trùng rồi thầy ơi!");
            } else {
                SinhVien st = new SinhVien();
                st.setName(txtHoTen.getText());
                st.setMarks(Double.parseDouble(txtDiem.getText()));
                st.setMajor(cbbNganh.getSelectedItem() + "");
                txtHocLuc.setText(st.getGrade());
                chkBonus.setSelected(st.isBonus());
                lstStudent.add(st);
                fillToTable();
            }
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        LBL1 = new javax.swing.JLabel();
        lblHoTen = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        lblDiem = new javax.swing.JLabel();
        txtDiem = new javax.swing.JTextField();
        lblNganh = new javax.swing.JLabel();
        cbbNganh = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txtHocLuc = new javax.swing.JTextField();
        chkBonus = new javax.swing.JCheckBox();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnNhapMoi = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSinhVien = new javax.swing.JTable();
        btnTen = new javax.swing.JButton();
        btnDiem = new javax.swing.JButton();
        btnGhiFile = new javax.swing.JButton();
        btnDocFile = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LBL1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        LBL1.setText("QUẢN LÝ SINH VIÊN");

        lblHoTen.setText("Họ Và Tên");

        lblDiem.setText("ĐIỂM");

        lblNganh.setText("Ngành Học");

        cbbNganh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ứng Dụng Phần Mềm ", "Lập trình máy tính & thiết bị di động", "Thiết kế web", "Tự động hóa", "Quản trị khách sạn" }));

        jLabel1.setText("HỌC LỰC");

        txtHocLuc.setEditable(false);
        txtHocLuc.setActionCommand("<Not Set>");

        chkBonus.setText("Có phần thưởng?");

        btnThem.setText("THÊM");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setText("XÓA");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnCapNhat.setText("CẬP NHẬT");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        btnNhapMoi.setText("NHẬP MỚI");
        btnNhapMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapMoiActionPerformed(evt);
            }
        });

        tblSinhVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "HỌ VÀ TÊN", "ĐIỂM", "NGÀNH", "HỌC LỰC", "Thưởng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblSinhVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSinhVienMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblSinhVien);

        btnTen.setText("Sắp Xếp theo tên");
        btnTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTenActionPerformed(evt);
            }
        });

        btnDiem.setText("Sắp xếp theo điểm");
        btnDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiemActionPerformed(evt);
            }
        });

        btnGhiFile.setText("Ghi File");
        btnGhiFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGhiFileActionPerformed(evt);
            }
        });

        btnDocFile.setText("Đọc File");
        btnDocFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocFileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHoTen)
                            .addComponent(lblDiem)
                            .addComponent(lblNganh)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDiem)
                            .addComponent(txtHoTen)
                            .addComponent(txtHocLuc)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbbNganh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(chkBonus))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addComponent(LBL1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnThem)
                                .addGap(18, 18, 18)
                                .addComponent(btnXoa)
                                .addGap(18, 18, 18)
                                .addComponent(btnCapNhat)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnGhiFile)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnDocFile))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnNhapMoi)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnTen)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnDiem)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LBL1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHoTen)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiem)
                    .addComponent(txtDiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNganh)
                    .addComponent(cbbNganh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtHocLuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkBonus)
                    .addComponent(btnGhiFile)
                    .addComponent(btnDocFile))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnXoa)
                    .addComponent(btnCapNhat)
                    .addComponent(btnNhapMoi)
                    .addComponent(btnTen)
                    .addComponent(btnDiem))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNhapMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapMoiActionPerformed
        // TODO add your handling code here:
        this.CapNhat();

    }//GEN-LAST:event_btnNhapMoiActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        this.themSinhVien();
        this.fillToTable();
        this.CapNhat();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        // TODO add your handling code here:
//        this.tblSinhVienMouseClicked(evt);
//        this.btnXoaActionPerformed(evt);
//        this.themSinhVien();

        int index = tblSinhVien.getSelectedRow();
        SinhVien st = lstStudent.get(index);
        st.setName(txtHoTen.getText());
        st.setMarks(Double.parseDouble(txtDiem.getText()));
        st.setMajor(cbbNganh.getSelectedItem() + "");
        fillToTable();
        this.CapNhat();
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        try {
            int index = this.tblSinhVien.getSelectedRow();
            lstStudent.remove(index);
            fillToTable();
            CapNhat();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "bạn có chọn dữ liệu đâu mà xóa!", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void tblSinhVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSinhVienMouseClicked
        // TODO add your handling code here:
        int row = this.tblSinhVien.getSelectedRow();
        if (row == -1) {
            return;
        } else {
            this.txtHoTen.setText(lstStudent.get(row).getName());
            this.txtDiem.setText(lstStudent.get(row).getMarks().toString());
            this.txtHocLuc.setText(lstStudent.get(row).getGrade());
            if (this.lstStudent.get(row).isBonus()== true) {
                this.chkBonus.setSelected(true);
            } else {
                this.chkBonus.setSelected(false);
            }
            for (int i = 0; i < this.cbbNganh.getItemCount(); i++) {
                if (this.cbbNganh.getItemAt(i)
                        .equals(lstStudent.get(row).getMajor())) {
                    this.cbbNganh.setSelectedIndex(i);
                }
            }
        }
    }//GEN-LAST:event_tblSinhVienMouseClicked

    private void btnTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTenActionPerformed
        // TODO add your handling code here:
        Comparator<SinhVien> com = new Comparator<SinhVien>(){
            @Override
            public int compare (SinhVien o1, SinhVien o2){
                return o1.name.compareTo(o2.name);
            }
        };
        Collections.sort(lstStudent, com);
        this.fillToTable();
    }//GEN-LAST:event_btnTenActionPerformed

    private void btnDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiemActionPerformed
        // TODO add your handling code here:
        Comparator<SinhVien> com = new Comparator<SinhVien>(){
            @Override
            public int compare (SinhVien o1, SinhVien o2){
                Double d1 = o1.marks;
                Double d2 = o2.marks;
                
                return d1.compareTo(d2);
            }
        };
        Collections.sort(lstStudent, com);
        this.fillToTable();
    }//GEN-LAST:event_btnDiemActionPerformed

    private void btnGhiFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGhiFileActionPerformed
        //Đọc dữ liệu từ ArrayList & ghi vào file
        
        try {
            FileOutputStream fos = new FileOutputStream("DemoObjectOI.txt");
            ObjectOutputStream oos = new ObjectOutputStream(fos);
            
            oos.writeObject(evt);
            oos.close();
            fos.close();
        } catch (Exception e) {
            e.printStackTrace();
            System.out.println("Ghi file thất bại");
        }
    }//GEN-LAST:event_btnGhiFileActionPerformed

    private void btnDocFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocFileActionPerformed
        // TODO add your handling code here:
        //Đọc Object từ file với ObjectInputStream
        
        this.fillToTable();
    }//GEN-LAST:event_btnDocFileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameQLSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameQLSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameQLSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameQLSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameQLSV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LBL1;
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnDiem;
    private javax.swing.JButton btnDocFile;
    private javax.swing.JButton btnGhiFile;
    private javax.swing.JButton btnNhapMoi;
    private javax.swing.JButton btnTen;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbbNganh;
    private javax.swing.JCheckBox chkBonus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblDiem;
    private javax.swing.JLabel lblHoTen;
    private javax.swing.JLabel lblNganh;
    private javax.swing.JTable tblSinhVien;
    private javax.swing.JTextField txtDiem;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtHocLuc;
    // End of variables declaration//GEN-END:variables

    private void tblSinhVienMouseClicked(ActionEvent evt) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

}
